//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StreamingRespirator.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StreamingRespirator.Properties.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Startup with windows과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ConfigWindow__ctlAutoStartup__Text {
            get {
                return ResourceManager.GetString("ConfigWindow__ctlAutoStartup__Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ConfigWindow__ctlCancel__Text {
            get {
                return ResourceManager.GetString("ConfigWindow__ctlCancel__Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ConfigWindow__ctlOK__Text {
            get {
                return ResourceManager.GetString("ConfigWindow__ctlOK__Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Proxy Port과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ConfigWindow__ctlPortLabel__Text {
            get {
                return ResourceManager.GetString("ConfigWindow__ctlPortLabel__Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Proxy option과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ConfigWindow__ctlProxyGroup__Text {
            get {
                return ResourceManager.GetString("ConfigWindow__ctlProxyGroup__Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show my retweet과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ConfigWindow__ctlShowMyRetweet__Text {
            get {
                return ResourceManager.GetString("ConfigWindow__ctlShowMyRetweet__Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show my retweeted tweets과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ConfigWindow__ctlShowRetweet__Text {
            get {
                return ResourceManager.GetString("ConfigWindow__ctlShowRetweet__Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Streamin option과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ConfigWindow__ctlStreamingGroup__Text {
            get {
                return ResourceManager.GetString("ConfigWindow__ctlStreamingGroup__Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use HTTPS proxy과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ConfigWindow__ctlUseHTTPS__Text {
            get {
                return ResourceManager.GetString("ConfigWindow__ctlUseHTTPS__Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Streaming Respirator Setting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ConfigWindow__Text {
            get {
                return ResourceManager.GetString("ConfigWindow__Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Proxy-related settings take effect after restart.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ConfigWindow_ApplyAfterRestart {
            get {
                return ResourceManager.GetString("ConfigWindow_ApplyAfterRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   When using an HTTPS proxy, security vulnerabilities can exist.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ConfigWindow_HttpsWarning {
            get {
                return ResourceManager.GetString("ConfigWindow_HttpsWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loading.
        ///Please wait a moment.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LoginWindowWeb__m_label__Text {
            get {
                return ResourceManager.GetString("LoginWindowWeb__m_label__Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add twitter account과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LoginWindowWeb__Text {
            get {
                return ResourceManager.GetString("LoginWindowWeb__Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to add account과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LoginWindowWeb_AddError {
            get {
                return ResourceManager.GetString("LoginWindowWeb_AddError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New account {0} has been added.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LoginWindowWeb_AddSuccess {
            get {
                return ResourceManager.GetString("LoginWindowWeb_AddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add account과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MainContext__m_stripAdd__Text {
            get {
                return ResourceManager.GetString("MainContext__m_stripAdd__Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MainContext__m_stripConfig__Text {
            get {
                return ResourceManager.GetString("MainContext__m_stripConfig__Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Quit과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MainContext__m_stripExit__Text {
            get {
                return ResourceManager.GetString("MainContext__m_stripExit__Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Refresh과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MainContext_Client_Refresh {
            get {
                return ResourceManager.GetString("MainContext_Client_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove account과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MainContext_Client_Remove {
            get {
                return ResourceManager.GetString("MainContext_Client_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No account has been added.
        ///
        ///Please add an account.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MainContext_NoAccount {
            get {
                return ResourceManager.GetString("MainContext_NoAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An error occurred while staring the Streaming Respirator.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MainContext_StartError {
            get {
                return ResourceManager.GetString("MainContext_StartError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Streaming Respirator과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There&apos;s a new update available.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NewUpdate {
            get {
                return ResourceManager.GetString("NewUpdate", resourceCulture);
            }
        }
    }
}
