version: 0.0.0.{build}

assembly_info:
  patch: true
  file: StreamingRespirator\Properties\AssemblyInfo.cs
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

branches:
  only:
    - master
build:
  project: StreamingRespirator.sln

image: Previous Visual Studio 2019
configuration: Release
platform: Any CPU

environment:
  SIGNTOOL: C:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\x64\signtool.exe
  pfx_password:
    secure: 05Z+DJrJSTS5M1rFyx3Iagaz8TlNELOI4BLy3dvCFs1fpRalCSCd+D0RZossungT+vqhORuzaengXhWwY9oeoJWeXxRbMtTyFLySwbS52hA=

before_build:
- cmd: |
    nuget restore

after_build:
- cmd: |
    "%SIGNTOOL%" sign /tr "http://timestamp.digicert.com" /td sha256 /fd sha256 /p %pfx_password% /f "StreamingRespirator.p12" "bin\Release\StreamingRespirator.exe"

artifacts:
-  path: bin\Release\StreamingRespirator.exe
   name: executable

deploy:
- provider: GitHub
  auth_token:
    secure: hTayr5LL8X8BFAdogH7iHegb3vRl9VSTnFEN/F5tWH5Y2hzNMEC6d+R+Pja3T8CL
  draft: true
  prerelease: false
  force_update: false
  artifact: executable

test: off
