version: 0.0.0.{build}

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: {version}
  package_version: {version}
  assembly_version: {version}
  file_version: {version}
  informational_version: {version}

branches:
  only:
    - master
build:
  project: StreamingRespirator.sln

image: Previous Visual Studio 2019
configuration: Release
platform: Any CPU

before_build:
- cmd: nuget restore

artifacts:
-  path: bin\Release\StreamingRespirator.exe
   name: executable

deploy:
- provider: GitHub
  auth_token:
    secure: hTayr5LL8X8BFAdogH7iHegb3vRl9VSTnFEN/F5tWH5Y2hzNMEC6d+R+Pja3T8CL
  draft: true
  prerelease: false
  force_update: false
  artifact: executable

test: off
